name: CI
on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node-version }}

    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node-version: ["14"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test

env:
  CI: true
